### ISSUE TITLE
[BUG] AppInfo::launch_uris_async_future does not launch app

### ISSUE THREAD

**Issue by DorianRudolph** [gtk-rs/gtk-rs-core#287]
The function `AppInfo::launch_uris_async_future` does not launch the program.
The `block_on` command waits infinitely.
The code is below. There was no backtrace.

Admittedly, I am not quite certain whether my code is correct. 

main.rs:
```rust
use gdk::prelude::AppInfoExtManual;
use gio::{AppInfo, traits::AppInfoExt, glib::MainContext};
use futures::executor::block_on;

fn main() {
    gdk::init();
    MainContext::default().push_thread_default(); // otherwise future cannot be polled
    let context = gdk::Display::default().unwrap().app_launch_context().unwrap();
    for info in AppInfo::all() {
        if info.display_name() == "Konsole" {
            // info.launch_uris(&[], Some(&context)).expect("Error"); // works
            let future = info.launch_uris_async_future(&[], Some(&context));
            block_on(future).expect("Error"); 
        }
    }
}
```
cargo.toml:
```toml
[package]
name = "appinfotest"
version = "0.1.0"
edition = "2018"
[dependencies]
gio = { version = "0.14.8", features = ['v2_60'] }
gdk = "0.14.3"
futures = "0.3.17"
```
