### ISSUE TITLE
glib: Provide bindings for glib::markup_escape_text

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#489]
The function https://docs.gtk.org/glib/func.markup_escape_text.html is very useful to escape markup, it might take into account different gtk/pango-related details that other escapers might not do.

Looking at `glib/Gir.toml` I see
```toml
    [[object.function]]
    pattern = "markup_.*"
    ignore = true # they are supposed to be used with MarkupParser, which doesn't have safe bindings
```
but I do not think the reasoning applies for this function.
